### ISSUE TITLE
Support errorinfo addition to core ZC

### ISSUE THREAD

**Issue by neekfenwick** [scottcwilson/Email_Archive_Manager#1]
See Issue at https://github.com/zencart/zencart/discussions/6449

Initial version would not provide detailed text search, just the ability to filter by rows that have an errorinfo value and display it.

**Comment by neekfenwick** [comment]
Some points:
- The addon uses a constant and string truncation to display "..." on the end of the Subject line in the table, but I imagine this is very old code and it seems more elegant these days to use CSS and `text-overflow: ellipsis` so that the amount of text displayed before the "..." is variable.  The Subject line is unlikely to be so long as to make storing the entire string in the `<td>` a problem.  I have used the CSS approach when displaying the ErrorInfo text in the table; is it OK if I make a similar update to the subject field?
- The date picker dropdown buttons are rendering with a large amount of margin because of a quirk in the core ZC stylesheet, admin/css/stylesheet.css defines `.smallText a img { margin-bottom: 16px }` and because the down arrow is an `img` this causes layout breakage.  I can change it to use a FontAwesome glyph instead of an image to avoid this problem: `<i class="fa-solid fa-caret-down"></i>`  *edit* On closer inspection, this use of `<img>` is hardcoded into spiffycal, so I'll try to look at what we can do there (upgrade? fork?).
- It's still using `rowOverEffect`/`rowOutEffect` event handlers on table rows to change `class` on the row to achieve a highlight effect, when CSS for many years has offered `:hover` pseudo classes (and the even/odd colouring is also a really old approach).  Do you know what the position is in Zen Cart of deprecating these ancient techniques and using a more modern approach via `:hover` and `:nth-child(odd)`/`:nth-child(even)`?  Maybe this belongs in a PR on core zencart?

**Comment by neekfenwick** [comment]
Just for my sanity, why is this repo still being maintained, if there is now a more 'core' repo https://github.com/zencart/email-archive-manager ?

Also the addon available at https://www.zen-cart.com/downloads.php?do=file&id=101 and docs at https://docs.zen-cart.com/user/email/email_archive_manager/

Is this stuff just waiting for some admin work before they are deprecated in favour of the core one?

**Comment by scottcwilson** [comment]
> why is this repo still being maintained

Bear in mind that the new repo is less than a week old.  I have updated the README in mine to point to the new one. 

The addon in the plugins library will be updated with the new archive manager as soon as possible.  Note the Github button on that addon's page points to Chris' repo.

The docs point to the plugins library.  Many users are not sophisticated enough to use Github; we put plugins in Github for *other programmers*, not for users.
